export const registerTypes = {
    REGISTER: 'REGISTER',
    UPDATE_BUCKETKEY: 'UPDATE_BUCKETKEY',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_FIRST_NAME: 'UPDATE_FIRST_NAME',
    UPDATE_LAST_NAME: 'UPDATE_LAST_NAME',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_USERNAME: 'UPDATE_USERNAME'
  }