export const createPlaylistTypes= {
    ADD_INPUT_TO_PLAYLIST: 'ADD_INPUT_TO_PLAYLIST',
    CLEAR_SONG_FROM_SUGGESTED_SONGS: 'CLEAR_SONG_FROM_SUGGESTED_SONGS',
    CLEAR_SUGGESTED_SONGS: 'CLEAR_SUGGESTED_SONGS',
    GET_ACCESS_TOKEN: 'GET_ACCESS_TOKEN',
    GET_SONGS_FROM_DATABASE: 'GET_SONGS_FROM_DATABASE',
    GET_SONGS_FROM_SPOTIFY_API: 'GET_SONGS_FROM_SPOTIFY_API',
    GET_SUGGESTED_SONGS: 'GET_SUGGESTED_SONGS',
    REMOVE_SONG_FROM_PLAYLIST: 'REMOVE_SONG_FROM_PLAYLIST',
    SET_PLAYLIST_OWNER: 'SET_PLAYLIST_OWNER',
    UPDATE_ARTIST_INPUT: 'UPDATE_ARTIST_INPUT',
    UPDATE_ERROR_MESSAGE: 'UPDATE_ERROR_MESSAGE',
    UPDATE_SONG_INPUT: 'UPDATE_SONG_INPUT'
}